---
title: "00_Generate dataset"
author: "Nadege Belouard"
date: "5/18/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

Let's generate a dataset to test the jump identification script

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(here)
library(magrittr)
library(sf)
library(stringr)
sf::sf_use_s2(FALSE)

# Create a folder if it does not exist
if (file.exists(file.path(here(),"data")) == FALSE){
  dir.create(file.path(here(),"data"))
}
```

Create coordinates on a single axis: diffusive spread, jumps, and negatives
```{r create coordinates}
set.seed(2022) #for reproducibility

# Diffusers
diffusers <- rbind(
# year1
data.frame(dist = abs(rnorm(n = 100, mean = 0, sd = 0.00500)), bio_year = 2012),
# year2
data.frame(dist = abs(rnorm(n = 500, mean = 0, sd = 0.05000)), bio_year = 2013),
# year3
data.frame(dist = abs(rnorm(n = 2000, mean = 0, sd = 0.10000)), bio_year = 2014),
# year4
data.frame(dist = abs(rnorm(n = 10000, mean = 0, sd = 0.15000)), bio_year = 2015)
)

diffusers %<>% mutate(status = "diffusers")


# Jumps
jumps <- rbind(
  # year 3
  data.frame(dist = abs(rnorm(n = 5, mean = 1.50000, sd = 0.10000)), bio_year = 2014),
  # year 4           
data.frame(dist = abs(rnorm(n = 10, mean = 1.70000, sd = 0.20000)), bio_year = 2015)
)

jumps %<>% mutate(status = "jumpers")

# Negatives
negatives <- rbind(
# year1
data.frame(dist = abs(rnorm(n = 200, mean = 0, sd = 0.00600)), bio_year = 2012),
# year2
data.frame(dist = abs(rnorm(n = 1000, mean = 0, sd = 0.10000)), bio_year = 2013),
# year3
data.frame(dist = abs(rnorm(n = 4000, mean = 0, sd = 0.15000)), bio_year = 2014),
# year4
data.frame(dist = abs(rnorm(n = 20000, mean = 0, sd = 0.20000)), bio_year = 2015)
)

negatives %<>% mutate(status = "negatives")
```


Make the dataset
```{r create dataset}
dataset <- rbind(negatives, diffusers, jumps)
dataset$status <- factor(dataset$status, levels = c("diffusers", "jumpers", "negatives"))

# show me the points
ggplot(dataset, aes(x = dist)) +
geom_histogram(aes(fill = status))
```

Spread out points on a circle
```{r spread out points}
dataset %<>% 
  mutate(theta = runif(length(dataset$dist), min = 0, max = 2*pi)) %>% 
  mutate(longitude = round(dist * cos(theta) - 85,5), latitude = round(dist * sin(theta) + 40, 5))

dataset$bio_year <- as.factor(dataset$bio_year)
dataset %<>% arrange(desc(bio_year))

```

Map points
```{r show points}
# extracts a map of the States and recodes state labels to show the two-letter code rather than the full state name.

# obtaining simple feature objects for states and finding centroids for label positioning
states <- sf::st_as_sf(maps::map("state", plot = FALSE, fill = TRUE))
# sf::st_as_sf(maps::map("county", plot = TRUE, fill = FALSE))
states <- cbind(states, st_coordinates(st_centroid(states)))

# making table key for state 2-letter abbreviations
# the vectors state.abb and state.name contains strings of all
# US states and abbreviations
state_abbr <- tibble(state.name = str_to_lower(state.name), state.abb) %>%
  left_join(tibble(ID = states$ID), ., by = c(ID = "state.name")) %>%
  mutate(state.abb = replace_na(state.abb, ""))

# adding 2-letter codes to sf
states$code <- state_abbr$state.abb



# Visualize points and chull
ggplot(data = states, fill = "white") +
  geom_sf() +
  geom_point(data = dataset, aes(x = longitude, y = latitude, col = status)) +
  labs(x = "Longitude", y = "Latitude") +
  geom_text(data = states,
            aes(X, Y, label = code), size = 4) +
  coord_sf(xlim = c(-88, -82), ylim = c(38, 43))

```

Save the dataset
```{r function for creating dataset}
save(dataset, file = file.path(here(), "data", "dataset.Rda"))
```
